//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DataModelSample.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class footertext
    {
        public int footertext_id { get; set; }
        public string footertext_title { get; set; }
    
        public virtual footertextdesc footertextdesc { get; set; }
    }
}
